# Generated by Django 4.2.1 on 2023-05-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userregistration_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='confirm_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
